openapi: 3.0.0
info:
  title: AI Content API
  version: 1.0.0

servers:
- url: https://d5d71lui36v3bq8i4no1.laqt4bj7.apigw.yandexcloud.net
paths:
  /generate:
    options:
      summary: CORS preflight
      responses:
        '204':
          description: No Content
      x-yc-apigateway-integration:
        type: dummy
        content:
          '*/*': ''
        http_code: 204
        http_headers:
          Access-Control-Allow-Origin: "*"
          Access-Control-Allow-Methods: "POST, OPTIONS"
          Access-Control-Allow-Headers: "Content-Type"
    post:
      summary: Generate text
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e3kea27jfgs5hvos8k   # твой ID функции
      responses:
        '200':
          description: OK
